---
- name: Demonstrate usage of variables
  hosts: ansible_nodes
  gather_facts: false

  vars:
    base_dir: /tmp/ansible_vars
    files:
      - info.txt
      - data.log
      - config.ini

  tasks:
    - name: Create base directory
      ansible.builtin.file:
        path: "{{ base_dir }}"
        state: directory
        mode: "0755"

    - name: Create multiple files in base directory using loop
      ansible.builtin.file:
        path: "{{ base_dir }}/{{ item }}"
        state: touch
      loop: "{{ files }}"
